sudo: required
language: python
python: 
  - "3.6"
install:
  - pip3 install web3==3.16.5
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -q
  - sudo apt-get install solc -y
  - sudo apt-get install ethereum -y
before_script:
    geth --dev --rpc --rpccorsdomain "http://localhost:8545" --rpcapi="db,eth,net,web3,personal,web3" --targetgaslimit '9000000'
script:
    bash scripts/build.sh
after_script:
    pkill geth
    

