sudo: required
language: python
python: 
  - "3.6"
install:
  - pip3 install web3==3.16.5
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update -q
  - sudo apt-get install solc -y
script:
    bash scripts/build.sh

